### ISSUE TITLE
Prep 3.4.2 Release

### ISSUE THREAD

**Issue by ewr** [SCPR/KPCC-iPhone#108]
* [x] Fix UI for KPCC Plus stream selection (as discovered in #104)
* [x] Determine pledge drive state in a less resource-intensive way
* [x] Fix mysterious crash in [__NSArrayI objectAtIndex:]: index 0 beyond bounds for empty array
* [x] Try to fix iOS7 crash (#111)
* [x] Fix alarm clock for early ios8/ios7 (#105)
* [x] Fix handling for null on-demand duration (#101)

Stretch goals:
* [x] #76 - session timeout change
* [x] #86 - Spoken Audio mode
